env:
  browser: true
  commonjs: true
  node: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  curly:
    - warn
  react/prop-types: 0